/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package springBootInitialDemo;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;


@SpringBootApplication
public class App {

    public static void main(String[] args) {

        SpringApplication.run(App.class, args);
    }
    
    
    @GetMapping("/hello")
    public String hello(@RequestParam(value = "nom", defaultValue = "world") String nom) {
    	return "hello "+nom;
    }
    
    
    @GetMapping("/")
    public String Arrel() {
    	return "hello world";
    }
    
    
    
    
}
